POWERLEVEL9K_MODE='nerdfont-complete'
#ZSH_THEME="powerlevel9k/powerlevel9k"

set_wifi(){
	wifi_signal=$(nmcli device wifi | grep -E "\*" | awk '{print $8}')

	POWERLEVEL9K_CUSTOM_WIFI_NAME_FOREGROUND="black"
	POWERLEVEL9K_CUSTOM_WIFI_RATE_FOREGROUND="black"
	POWERLEVEL9K_CUSTOM_WIFI_BARS_AND_SIGNAL_FOREGROUND="black"

	POWERLEVEL9K_CUSTOM_WIFI_NAME_BACKGROUND="046"
	POWERLEVEL9K_CUSTOM_WIFI_RATE_BACKGROUND="046"
	POWERLEVEL9K_CUSTOM_WIFI_BARS_AND_SIGNAL_BACKGROUND="046"

	if [[ $wifi_signal -lt 50 ]] ; then
		POWERLEVEL9K_CUSTOM_WIFI_NAME_BACKGROUND="red"
		POWERLEVEL9K_CUSTOM_WIFI_RATE_BACKGROUND="red"
		POWERLEVEL9K_CUSTOM_WIFI_BARS_AND_SIGNAL_BACKGROUND="red"
	elif [[ $wifi_signal -lt 75 ]] ; then
		POWERLEVEL9K_CUSTOM_WIFI_NAME_BACKGROUND="yellow"
		POWERLEVEL9K_CUSTOM_WIFI_RATE_BACKGROUND="yellow"
		POWERLEVEL9K_CUSTOM_WIFI_BARS_AND_SIGNAL_BACKGROUND="yellow"
	fi
}

set_wifi

wifi_name(){
	local name=$(nmcli device wifi | grep -E "\*" | awk '{print $3}')
	echo "\uf502 $name"
}

wifi_rate(){
	local rate=$(nmcli device wifi | grep -E "\*" | awk '{print $6}')
	echo "\uf0e7 $rate Mbit/s"
}

wifi_bars_and_signal(){
	local bars=$(nmcli device wifi | grep -E "\*" | awk '{print $9}')
	echo "$bars $wifi_signal %%"
}

POWERLEVEL9K_CUSTOM_WIFI_NAME="wifi_name"
POWERLEVEL9K_CUSTOM_WIFI_RATE="wifi_rate"
POWERLEVEL9K_CUSTOM_WIFI_BARS_AND_SIGNAL="wifi_bars_and_signal"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true 
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true 
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
	os_icon date time newline 
	custom_wifi_name custom_wifi_rate custom_wifi_bars_and_signal newline
	background_jobs ram load swap disk_usage newline 
	php_version java_version node_version newline 
	dir dir_writable vcs 
)


POWERLEVEL9K_OS_ICON_BACKGROUND="253"
POWERLEVEL9K_OS_ICON_FOREGROUND="002"

POWERLEVEL9K_PHP_VERSION_BACKGROUND="010"
POWERLEVEL9K_PHP_VERSION_FOREGROUND="000"

POWERLEVEL9K_JAVA_VERSION_BACKGROUND="196"
POWERLEVEL9K_JAVA_VERSION_FOREGROUND="000"

POWERLEVEL9K_NODE_VERSION_BACKGROUND="082"
POWERLEVEL9K_NODE_VERSION_FOREGROUND="000"

POWERLEVEL9K_RAM_BACKGROUND="202"
POWERLEVEL9K_SWAP_BACKGROUND="226"


POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(history status_joined)
POWERLEVEL9K_DATE_FORMAT=%D{%Y.%m.%d}
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true 

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='166'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='000'

POWERLEVEL9K_DIR_ETC_BACKGROUND='226'
POWERLEVEL9K_DIR_ETC_FOREGROUND='000'
POWERLEVEL9K_DIR_HOME_BACKGROUND='044'
POWERLEVEL9K_DIR_HOME_FOREGROUND='000'

POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='044'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='000'

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='000'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='048'
POWERLEVEL9K_STATUS_OK_BACKGROUND='046'
POWERLEVEL9K_STATUS_OK_FOREGROUND='000'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='160'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='000'

POWERLEVEL9K_VCS_CLEAN_BACKGROUND='226'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='000'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='199'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='000'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='226'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='000'

POWERLEVEL9K_TIME_BACKGROUND='202'
POWERLEVEL9K_TIME_FOREGROUND='000'

source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme
